version: '3'

services:
  stock-predict-api:
    build: .
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    container_name: "${DOCKER_CONTAINER_NAME}"
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - stock-predict-postgres
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    networks:
      - stock-predict_net

  stock-predict-postgres:
    image: postgres:15
    container_name: stock-predict-postgres
    volumes:
      - /home/stock-predict-cms/postgres-15:/var/lib/postgresql/data
    env_file:
      - .env.production
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - stock-predict_net

networks:
  stock-predict_net:
    driver: bridge
