version: '3'

services:
  stock-predict-api:
    image: lamnh/stock-predict-api:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - /.env.production
    depends_on:
      - stock-predict-postgres
    networks:
      - stock-predict-net
    restart: always

  stock-predict-postgres:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stock_predict_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stock_predict_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stock-predict-net
    restart: always

networks:
  stock-predict-net:
