# Generated by Django 4.2.4 on 2024-02-20 01:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_alter_configurationtype_configuration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pid', models.CharField(choices=[('BUY', 'Buying'), ('SELL', 'Selling'), ('FOLLOW', 'Following')], max_length=50)),
                ('max_volume_buy', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_buy', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_sell', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('aver_price_buy', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_configuration', to='configuration.configuration')),
            ],
            options={
                'db_table': 'trading',
            },
        ),
    ]
