# Generated by Django 5.0.6 on 2024-08-06 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trading',
            name='trading_status',
            field=models.CharField(choices=[('ready_to_buy', 'Ready to Buy'), ('buying_processing', 'Buying Processing'), ('ready_to_sell', 'Ready to Sell'), ('selling_processing', 'Selling Processing'), ('completed', 'Completed')], default='ready_to_buy', max_length=20),
        ),
    ]
