# Generated by Django 5.0.6 on 2024-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_trading_last_status_change_trading_trading_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='trading_status',
            field=models.CharField(choices=[('waiting_to_buy', 'Waiting to Buy'), ('ready_to_buy', 'Ready to Buy'), ('buying_processing', 'Buying Processing'), ('waiting_to_sell', 'Waiting to Sell'), ('ready_to_sell', 'Ready to Sell'), ('selling_processing', 'Selling Processing'), ('completed', 'Completed')], default='ready_to_buy', max_length=20),
        ),
    ]
