# Generated by Django 4.2.4 on 2024-02-20 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockM5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('open', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'stock_m5',
            },
        ),
        migrations.CreateModel(
            name='StockM15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('open', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'stock_m15',
            },
        ),
        migrations.CreateModel(
            name='StockM1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('open', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'stock_m1',
            },
        ),
        migrations.CreateModel(
            name='StockH1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('open', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'stock_h1',
            },
        ),
                migrations.CreateModel(
            name='StockD1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('open', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'stock_d1',
            },
        ),
    ]
