# Generated by Django 5.1.2 on 2025-05-21 05:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial_stock_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockW1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('open', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'W1',
            },
        ),
    ]
