from enum import Enum


class SignalTelegramEnum(Enum):
    NOTIFY_RUNNING = 'Notify Running '
    NOTIFY_LOGIN = 'Notify Login'
    LOGIN_SUCCESS = 'Login Success'
    LOGIN_FAILED = 'Login Failed'
    BUY_SUCCESS = 'Buy Success'
    BUY_REQUEST_SUCCESS = 'Buy Request Success'
    BUY_FAILED = 'Buy Failed'
    BUY_REQUEST_FAILED = 'Buy Request Failed'
    BUY_FAILED_UPDATE = 'Buy Failed Update'
    SESSION_FAILED = 'Session Failed'
    SELL_SUCCESS = 'Sell Success'
    SELL_REQUEST_SUCCESS = 'Sell Request Success'
    SELL_FAILED = 'Sell Failed'
    SELL_REQUEST_FAILED = 'Sell Request Failed'
    TAKE_PROFIT_FAILED = 'Take Profit Failed'
    SELL_FAILED_UPDATE = 'Sell Failed Update'
    STOPLOSS = 'Stoploss'
    TAKEPROFIT = 'Take Profit'
    DEFAULT = 'Default'
    BUY_ORDER_OVERRAL = 'Buy Order Overral'
    BUY_UPDATE_OVERRAL = 'Buy Order Update Overral'
    BUY_CANCEL_OVERRAL = 'Buy Order Cancel Overral'
    BUY_MATCHED_OVERRAL = 'Buy Order Matched Overral'
    BUY_ORDER_DETAIL = 'Buy Order Detail'
    BUY_UPDATE_DETAIL = 'Buy Update Detail'
    BUY_CANCEL_DETAIL = 'Buy Cancel Detail'
    BUY_MATCHED_DETAIL = 'Buy Matched Detail'       
    SELL_ORDER_OVERRAL = 'Sell Order Overral'
    SELL_UPDATE_OVERRAL = 'Sell Update Overral'
    SELL_CANCEL_OVERRAL = 'Sell Cancel Overral'
    SELL_MATCHED_OVERRAL = 'Sell Matched Overral'
    SELL_ORDER_DETAIL = 'Sell Order Detail'
    SELL_UPDATE_DETAIL = 'Sell Update Detail'
    SELL_CANCEL_DETAIL = 'Sell Cancel Detail'
    SELL_MATCHED_DETAIL = 'Sell Matched Detail'
