# Generated by Django 4.2.4 on 2024-02-17 16:54

import common.validation_data
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def init_data_configuration_type(apps, schema_editor):
    ConfigurationType = apps.get_model('configuration', 'ConfigurationType')
    init_data = [
        {
            'name': 'template',
            'configuration_type': 'template'
        },
        {
            'name': 'trading',
            'configuration_type': 'trading'
        },
        {
            'name': 'following',
            'configuration_type': 'following'
        },
        {
            'name': 'overview',
            'configuration_type': 'overview'       
        }
    ]
    
    for data in init_data:
        ConfigurationType.objects.create(**data)
        
def init_data_candle(apps, schema_editor):
    Candle = apps.get_model('configuration', 'Candle')
    init_data = [
        {
            'name': 'D1',
            'candle': 'D1'
        },
        {
            'name': 'H1',
            'candle': 'H1'
        },
        {
            'name': 'M15',
            'candle': 'M15'
        },
        {
            'name': 'M5',
            'candle': 'M5'
        },
        {
            'name': 'M1',
            'candle': 'M1'
        },
    ]
    
    for data in init_data:
        Candle.objects.create(**data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('candle', models.CharField(choices=[('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1')], max_length=50)),
            ],
            options={
                'db_table': 'candle',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('configuration_type', models.CharField(choices=[('TEMPLATE', 'template'), ('TRADING', 'trading'), ('FOLLOWING', 'following')], max_length=50)),
            ],
            options={
                'db_table': 'configuration_type',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField(default=True)),
                ('is_sell', models.BooleanField(default=True)),
                ('is_use_vnindex_config', models.BooleanField(default=True)),
                ('is_use_stock_config', models.BooleanField(default=True)),
                ('is_use_price_to_buy', models.BooleanField(default=False)),
                ('price_to_buy_now', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_use_stoploss', models.BooleanField(default=False)),
                ('percent_to_stoploss', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_use_takeprofit', models.BooleanField(default=False)),
                ('percent_to_takeprofit', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_update_volume_buy', models.BooleanField(default=False)),
                ('volume_to_buy', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_time_use_buy_only_trading', models.DateTimeField(null=True)),
                ('last_time_use_sell_only_trading', models.DateTimeField(null=True)),
                ('min_vnindex_config_vnindex_buy', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_vnindex_config_vnindex_buy', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('vnindex_config_use_min_vnindex_buy', models.BooleanField(default=True)),
                ('vnindex_config_use_max_vnindex_buy', models.BooleanField(default=True)),
                ('vnindex_config_min_vnindex_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_min_vnindex_buy_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_max_vnindex_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_max_vnindex_buy_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_rsi_to_buy', models.BooleanField(default=True)),
                ('vnindex_config_use_rsi_reversed_increase', models.BooleanField(default=True)),
                ('vnindex_config_value_rsi_to_buy', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vnindex_config_rsi_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_rsi_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_rsi_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_rsi_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_stoch_rsi_to_buy', models.BooleanField(default=True)),
                ('vnindex_config_use_stoch_rsi_reversed_increase', models.BooleanField(default=True)),
                ('vnindex_config_value_stoch_rsi_to_buy', models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vnindex_config_stoch_rsi_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_stoch_rsi_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_stoch_rsi_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_stoch_rsi_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_macd_to_buy', models.BooleanField(default=True)),
                ('vnindex_config_use_macd_reversed_increase', models.BooleanField(default=True)),
                ('vnindex_config_value_macd_to_buy', models.FloatField(default=0)),
                ('vnindex_config_macd_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_macd_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_macd_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_macd_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_histogram_reversed_increase', models.BooleanField(default=True)),
                ('vnindex_config_histogram_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_histogram_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_volume_to_buy', models.BooleanField(default=True)),
                ('vnindex_config_volume_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_volume_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_bolinger_to_buy', models.BooleanField(default=True)),
                ('vnindex_config_bolinger_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_bolinger_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('min_vnindex_config_vnindex_sell', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_vnindex_config_vnindex_sell', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('vnindex_config_use_min_vnindex_sell', models.BooleanField(default=True)),
                ('vnindex_config_use_max_vnindex_sell', models.BooleanField(default=True)),
                ('vnindex_config_min_vnindex_sell_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_min_vnindex_sell_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_max_vnindex_sell_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_max_vnindex_sell_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_rsi_to_sell', models.BooleanField(default=True)),
                ('vnindex_config_use_rsi_reversed_decrease', models.BooleanField(default=True)),
                ('vnindex_config_value_rsi_to_sell', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vnindex_config_rsi_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_rsi_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_rsi_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_rsi_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_stoch_rsi_to_sell', models.BooleanField(default=True)),
                ('vnindex_config_use_stoch_rsi_reversed_decrease', models.BooleanField(default=True)),
                ('vnindex_config_value_stoch_rsi_to_sell', models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vnindex_config_stoch_rsi_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_stoch_rsi_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_stoch_rsi_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_stoch_rsi_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_macd_to_sell', models.BooleanField(default=True)),
                ('vnindex_config_use_macd_reversed_decrease', models.BooleanField(default=True)),
                ('vnindex_config_value_macd_to_sell', models.FloatField(default=0)),
                ('vnindex_config_macd_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_macd_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_macd_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_macd_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_histogram_reversed_decrease', models.BooleanField(default=True)),
                ('vnindex_config_histogram_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_histogram_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('vnindex_config_use_bolinger_to_sell', models.BooleanField(default=True)),
                ('vnindex_config_bolinger_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('vnindex_config_bolinger_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_num_player', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_use_rsi_to_buy', models.BooleanField(default=True)),
                ('stock_config_use_rsi_reversed_increase', models.BooleanField(default=True)),
                ('stock_config_value_rsi_to_buy', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock_config_rsi_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_rsi_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_rsi_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_rsi_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_stoch_rsi_to_buy', models.BooleanField(default=True)),
                ('stock_config_use_stoch_rsi_reversed_increase', models.BooleanField(default=True)),
                ('stock_config_value_stoch_rsi_to_buy', models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock_config_stoch_rsi_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_stoch_rsi_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_stoch_rsi_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_stoch_rsi_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_macd_to_buy', models.BooleanField(default=True)),
                ('stock_config_use_macd_reversed_increase', models.BooleanField(default=True)),
                ('stock_config_value_macd_to_buy', models.FloatField(default=0)),
                ('stock_config_macd_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_macd_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_macd_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_macd_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_histogram_reversed_increase', models.BooleanField(default=True)),
                ('stock_config_histogram_reversed_increase_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_histogram_reversed_increase_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_volume_to_buy', models.BooleanField(default=True)),
                ('stock_config_volume_to_buy_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_volume_to_buy_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_rsi_to_sell', models.BooleanField(default=True)),
                ('stock_config_use_rsi_reversed_decrease', models.BooleanField(default=True)),
                ('stock_config_value_rsi_to_sell', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock_config_rsi_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_rsi_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_rsi_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_rsi_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_stoch_rsi_to_sell', models.BooleanField(default=True)),
                ('stock_config_use_stoch_rsi_reversed_decrease', models.BooleanField(default=True)),
                ('stock_config_value_stoch_rsi_to_sell', models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock_config_stoch_rsi_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_stoch_rsi_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_stoch_rsi_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_stoch_rsi_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_macd_to_sell', models.BooleanField(default=True)),
                ('stock_config_use_macd_reversed_decrease', models.BooleanField(default=True)),
                ('stock_config_value_macd_to_sell', models.FloatField(default=0)),
                ('stock_config_macd_to_sell_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_macd_to_sell_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_macd_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_macd_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_use_histogram_reversed_decrease', models.BooleanField(default=True)),
                ('stock_config_histogram_reversed_decrease_necessary_condition', models.BooleanField(default=False)),
                ('stock_config_histogram_reversed_decrease_sufficient_condition', models.BooleanField(default=False)),
                ('stock_config_time_to_buy', models.FloatField(default=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_time_update_pid_buy', models.FloatField(default=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_is_mode_sensitive_buy', models.BooleanField(default=True, null=True)),
                ('stock_config_percent_sensitive_buy', models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_number_pid_buy_once_time', models.FloatField(default=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_percent_stock_buy_once_time', models.FloatField(default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_slippage_volume_buy_per_pid', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_slippage_buy', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_time_to_sell', models.FloatField(default=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_time_update_pid_sell', models.FloatField(default=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_is_mode_sensitive_sell', models.BooleanField(default=True, null=True)),
                ('stock_config_percent_sensitive_sell', models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_number_pid_sell_once_time', models.FloatField(default=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_config_percent_stock_sell_once_time', models.FloatField(default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_slippage_volume_sell_per_pid', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_slippage_sell', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_use_stop_loss_first_part', models.BooleanField(default=True, null=True)),
                ('stock_config_percent_stop_loss_sell_first', models.FloatField(default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_use_stop_loss_trigger', models.BooleanField(default=True, null=True)),
                ('stock_config_stop_loss_percent', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_use_stop_loss_second_part', models.BooleanField(default=True)),
                ('stock_config_percent_stop_loss_sell_second', models.FloatField(default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_use_take_profit_first_part', models.BooleanField(default=True, null=True)),
                ('stock_config_percent_take_profit_sell_first', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_use_take_profit_trigger', models.BooleanField(default=True, null=True)),
                ('stock_config_take_profit_percent', models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_use_take_profit_second_part', models.BooleanField(default=True, null=True)),
                ('stock_config_percent_take_profit_sell_second', models.FloatField(default=0.03, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock_config_is_use_time_to_buy', models.BooleanField(default=False, null=True)),
                ('stock_config_time_start_buy', models.TextField(default='09:30', null=True, validators=[common.validation_data.validate_time_format])),
                ('stock_config_time_end_buy', models.TextField(default='15:30', null=True, validators=[common.validation_data.validate_time_format])),
                ('stock_config_is_use_time_to_sell', models.BooleanField(default=False, null=True)),
                ('stock_config_time_start_sell', models.TextField(default='09:30', null=True, validators=[common.validation_data.validate_time_format])),
                ('stock_config_time_end_sell', models.TextField(default='15:30', null=True, validators=[common.validation_data.validate_time_format])),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('candle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.candle')),
                ('config_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.configurationtype')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuration',
                'unique_together': {('user', 'account', 'stock', 'config_type')},
            },
        ),
        migrations.RunPython(init_data_candle),
        migrations.RunPython(init_data_configuration_type),
    ]
