# Generated by Django 4.2.4 on 2024-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationtype',
            name='configuration_type',
            field=models.CharField(choices=[('TEMPLATE', 'template'), ('TRADING', 'trading'), ('FOLLOWING', 'following'), ('OVERVIEW', 'overview')], max_length=50),
        ),
    ]
