# Generated by Django 4.2.4 on 2024-02-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_configurationtype_configuration_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='max_vnindex_config_vnindex_buy',
            new_name='vnindex_config_max_vnindex_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='max_vnindex_config_vnindex_sell',
            new_name='vnindex_config_max_vnindex_sell',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='min_vnindex_config_vnindex_buy',
            new_name='vnindex_config_min_vnindex_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='min_vnindex_config_vnindex_sell',
            new_name='vnindex_config_min_vnindex_sell',
        ),
    ]
