# Generated by Django 5.0.6 on 2024-06-26 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accounttype_remove_account_balance_and_more'),
        ('configuration', '0003_rename_max_vnindex_config_vnindex_buy_configuration_vnindex_config_max_vnindex_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='level',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subaccount'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_num_player',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
