# Generated by Django 5.0.6 on 2024-06-28 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_configuration_level_alter_configuration_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='margin_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
