# Generated by Django 5.0.6 on 2024-08-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_configuration_margin_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_decrease_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_decrease_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_increase_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_increase_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_histogram_decrease',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_histogram_increase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_decrease_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_decrease_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_increase_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_increase_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_histogram_decrease',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_histogram_increase',
            field=models.BooleanField(default=True),
        ),
    ]
