# Generated by Django 5.1.2 on 2025-01-06 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_configuration_stock_config_macd_decrease_necessary_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_add_price_buy',
            field=models.FloatField(default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_sub_price_sell',
            field=models.FloatField(default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
