# Generated by Django 5.1.2 on 2025-01-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_configuration_stock_config_add_price_buy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_sub_price_sell',
            new_name='stock_config_add_price_sell',
        ),
    ]
