# Generated by Django 5.1.2 on 2025-02-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_rename_stock_config_sub_price_sell_configuration_stock_config_add_price_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_stoch_rsi_to_buy_obligatory_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_stoch_rsi_obl_to_buy',
            field=models.BooleanField(default=True),
        ),
    ]
