# Generated by Django 5.1.2 on 2025-02-11 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_configuration_stock_config_stoch_rsi_to_buy_obligatory_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_stoch_rsi_obl_to_buy',
            field=models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
