# Generated by Django 5.1.2 on 2025-02-20 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_configuration_stock_config_macd_reversed_increase_obligatory_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_macd_to_buy_obligatory_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_rsi_to_buy_obligatory_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_stoch_rsi_to_buy_obligatory_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_macd_obl_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_rsi_obl_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_stoch_rsi_obl_to_buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_value_macd_obl_to_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_value_rsi_obl_to_buy',
            field=models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_value_stoch_rsi_obl_to_buy',
            field=models.FloatField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
