# Generated by Django 5.1.2 on 2025-03-25 03:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_configuration_vnindex_config_macd_to_buy_obligatory_condition_and_more'),
        ('stock', '0002_initial_stock_chart_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuration',
            unique_together={('user', 'stock', 'config_type')},
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='account',
        ),
    ]
