# Generated by Django 5.1.2 on 2025-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_alter_configuration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_block_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_block_sell',
            field=models.BooleanField(default=False),
        ),
    ]
