# Generated by Django 5.1.2 on 2025-04-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_configuration_is_block_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='candle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_buy_set', to='configuration.candle'),
        ),
    ]
