# Generated by Django 5.1.2 on 2025-04-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_alter_configuration_candle'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='candle_sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_sell_set', to='configuration.candle'),
        ),
    ]
