# Generated by Django 5.1.2 on 2025-04-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_configuration_candle_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='candle_sell',
            field=models.CharField(choices=[('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1')], default='D1', max_length=50),
            preserve_default=False,
        ),
    ]
