# Generated by Django 5.1.2 on 2025-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0018_candle_candle_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_buy_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_sell_hand',
            field=models.BooleanField(default=False),
        ),
    ]
