# Generated by Django 5.1.2 on 2025-05-15 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0019_configuration_is_buy_hand_configuration_is_sell_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_trading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_first_buy',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
