# Generated by Django 5.1.2 on 2025-05-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0020_configuration_is_trading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_sell',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1')], max_length=50),
        ),
    ]
