# Generated by Django 5.1.2 on 2025-06-12 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0021_alter_candle_candle_alter_candle_candle_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_buy_foreign',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_buy_up',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_sell_down',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_sell_foreign',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_buy_foreign',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_buy_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_sell_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_sell_foreign',
            field=models.BooleanField(default=False),
        ),
    ]
