# Generated by Django 5.1.2 on 2025-06-13 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0022_configuration_stock_config_percent_buy_foreign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='stock_config_percent_buy_foreign',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='stock_config_percent_buy_up',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='stock_config_percent_sell_down',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='stock_config_percent_sell_foreign',
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_buy_foreign',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_buy_up',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_sell_down',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_sell_foreign',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_use_buy_foreign',
            field=models.BooleanField(default=False),
        ),
    ]
