# Generated by Django 5.1.2 on 2025-06-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0023_remove_configuration_stock_config_percent_buy_foreign_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_buy_up',
            new_name='stock_config_use_buy_up_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_sell_down',
            new_name='stock_config_use_sell_down_to_sell',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_buy_foreign',
            new_name='stock_config_value_buy_foreign_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_buy_up',
            new_name='stock_config_value_buy_up_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_sell_down',
            new_name='stock_config_value_sell_down_to_sell',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_sell_foreign',
            new_name='stock_config_value_sell_foreign_to_sell',
        ),
    ]
