# Generated by Django 5.1.2 on 2025-06-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0024_rename_stock_config_use_buy_up_configuration_stock_config_use_buy_up_to_buy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_buy_foreign',
            new_name='stock_config_use_buy_foreign_to_buy',
        ),
    ]
