# Generated by Django 5.1.2 on 2025-06-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0025_rename_stock_config_use_buy_foreign_configuration_stock_config_use_buy_foreign_to_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_buy_foreign_to_buy',
            new_name='stock_config_use_buy_foreign_obl_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_buy_up_to_buy',
            new_name='stock_config_use_buy_up_obl_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_sell_down_to_sell',
            new_name='stock_config_use_sell_down_obl_to_sell',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_use_sell_foreign',
            new_name='stock_config_use_sell_foreign_obl_to_sell',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_buy_foreign_to_buy',
            new_name='stock_config_value_buy_foreign_obl_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_buy_up_to_buy',
            new_name='stock_config_value_buy_up_obl_to_buy',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_sell_down_to_sell',
            new_name='stock_config_value_sell_down_obl_to_sell',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_value_sell_foreign_to_sell',
            new_name='stock_config_value_sell_foreign_obl_to_sell',
        ),
    ]
