# Generated by Django 5.1.2 on 2025-07-02 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0026_rename_stock_config_use_buy_foreign_to_buy_configuration_stock_config_use_buy_foreign_obl_to_buy_and'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_use_buy_up_obl_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_value_buy_foreign_obl_to_buy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_value_buy_up_obl_to_buy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_value_sell_down_obl_to_sell',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
