# Generated by Django 5.1.2 on 2025-07-02 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0027_alter_configuration_stock_config_use_buy_up_obl_to_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_bolinger_to_take_profit',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_bolinger_to_take_profit',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
