# Generated by Django 5.1.2 on 2025-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0028_configuration_stock_config_percent_bolinger_to_take_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='stock_config_percent_bolinger_to_take_profit',
            new_name='stock_config_percent_bolinger_a_part_to_take_profit',
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_bolinger_a_part_to_take_profit',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
