# Generated by Django 5.1.2 on 2025-08-27 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0029_rename_stock_config_percent_bolinger_to_take_profit_configuration_stock_config_percent_bolinger_a_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_volume_trade_obl_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_volume_trade_obl_to_buy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
