# Generated by Django 5.1.2 on 2025-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0030_configuration_stock_config_use_volume_trade_obl_to_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='nindex_config_histogram_to_buy_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_to_buy_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_to_buy_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_to_sell_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_histogram_to_sell_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_histogram_obl_to_buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_histogram_to_buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_histogram_to_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_histogram_obl_to_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_histogram_to_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_histogram_to_sell',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_to_buy_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_to_sell_necessary_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_histogram_to_sell_sufficient_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_histogram_obl_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_histogram_to_buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_histogram_to_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_value_histogram_obl_to_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_value_histogram_to_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_value_histogram_to_sell',
            field=models.FloatField(default=0),
        ),
    ]
