# Generated by Django 5.1.2 on 2025-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0031_configuration_nindex_config_histogram_to_buy_necessary_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_macd_obl_increase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_macd_obl_increase',
            field=models.BooleanField(default=False),
        ),
    ]
