# Generated by Django 5.1.2 on 2025-10-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0032_configuration_stock_config_use_macd_obl_increase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='nindex_config_histogram_to_buy_necessary_condition',
            new_name='vnindex_config_histogram_to_buy_necessary_condition',
        ),
    ]
