# Generated by Django 5.1.2 on 2025-10-10 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0033_rename_nindex_config_histogram_to_buy_necessary_condition_configuration_vnindex_config_histogram_to_'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_take_profit_sell_first_two',
            field=models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_take_profit_first_part_two',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_take_profit_second_part_two',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
