# Generated by Django 5.1.2 on 2025-10-11 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0034_configuration_stock_config_percent_take_profit_sell_first_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_take_profit_sell_second_two',
            field=models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
