# Generated by Django 4.2.4 on 2025-10-31 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0035_configuration_stock_config_percent_take_profit_sell_second_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_stoch_rsi_to_take_profit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_value_stoch_rsi_to_take_profit',
            field=models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
