# Generated by Django 4.2.4 on 2025-11-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0037_configuration_stock_config_percent_stoch_rsi_to_take_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_days_buy',
            field=models.CharField(blank=True, default='12345', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_days_sell',
            field=models.CharField(blank=True, default='12345', max_length=7, null=True),
        ),
    ]
