# Generated by Django 4.2.4 on 2025-11-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0038_configuration_stock_config_days_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_sma_increase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_sma_obl_increase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_sma_increase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vnindex_config_use_sma_obl_increase',
            field=models.BooleanField(default=False),
        ),
    ]
