# Generated by Django 4.2.4 on 2025-12-04 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0040_configuration_stock_config_sma_decrease_necessary_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_percent_rsi_decrease_to_take_profit',
            field=models.FloatField(default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_use_rsi_decrease_to_take_profit',
            field=models.BooleanField(default=True),
        ),
    ]
