# Generated by Django 4.2.4 on 2025-12-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0041_configuration_stock_config_percent_rsi_decrease_to_take_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='candle_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_buy_second_set', to='configuration.candle'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='candle_sell_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_sell_second_set', to='configuration.candle'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_use_candle_second',
            field=models.BooleanField(default=True),
        ),
    ]
