# Generated by Django 4.2.4 on 2025-12-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0042_configuration_candle_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='candle_second',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('NONE', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='candle',
            name='candle_sell_second',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('NONE', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('NONE', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_sell',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('NONE', 'None')], max_length=50),
        ),
    ]
