# Generated by Django 4.2.4 on 2025-12-17 03:02

from django.db import migrations, models


def convert_none_to_off(apps, schema_editor):
    """Chuyển đổi giá trị 'None' hoặc 'NONE' thành 'OFF' trong các trường candle"""
    Candle = apps.get_model('configuration', 'Candle')
    
    # Chuyển đổi candle_second từ 'None' hoặc 'NONE' sang 'OFF'
    Candle.objects.filter(candle_second__in=['None', 'NONE']).update(candle_second='OFF')
    
    # Chuyển đổi candle_sell_second từ 'None' hoặc 'NONE' sang 'OFF'
    Candle.objects.filter(candle_sell_second__in=['None', 'NONE']).update(candle_sell_second='OFF')
    
    # Chuyển đổi candle từ 'None' hoặc 'NONE' sang 'OFF' (nếu có)
    Candle.objects.filter(candle__in=['None', 'NONE']).update(candle='OFF')
    
    # Chuyển đổi candle_sell từ 'None' hoặc 'NONE' sang 'OFF' (nếu có)
    Candle.objects.filter(candle_sell__in=['None', 'NONE']).update(candle_sell='OFF')


def reverse_convert_off_to_none(apps, schema_editor):
    """Reverse migration: chuyển đổi 'OFF' về 'NONE' (nếu cần rollback)"""
    Candle = apps.get_model('configuration', 'Candle')
    
    Candle.objects.filter(candle_second='OFF').update(candle_second='NONE')
    Candle.objects.filter(candle_sell_second='OFF').update(candle_sell_second='NONE')
    Candle.objects.filter(candle='OFF').update(candle='NONE')
    Candle.objects.filter(candle_sell='OFF').update(candle_sell='NONE')


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0043_candle_candle_second_candle_candle_sell_second_and_more'),
    ]

    operations = [
        # Bước 1: Data migration - chuyển đổi 'None' hoặc 'NONE' thành 'OFF'
        migrations.RunPython(convert_none_to_off, reverse_convert_off_to_none),
        
        # Bước 2: Schema migration - thay đổi choices và default
        migrations.AlterField(
            model_name='candle',
            name='candle',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('OFF', 'Off')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_second',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('OFF', 'Off')], default='OFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_sell',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('OFF', 'Off')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_sell_second',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('OFF', 'Off')], default='OFF', max_length=50),
        ),
    ]
