# Generated by Django 4.2.4 on 2026-02-05 03:10

import common.validation_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0044_alter_candle_candle_alter_candle_candle_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_time_end_buy_second',
            field=models.TextField(default='15:30', null=True, validators=[common.validation_data.validate_time_format]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_time_start_buy_second',
            field=models.TextField(default='09:30', null=True, validators=[common.validation_data.validate_time_format]),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_second',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('OFF', 'Off')], default='Off', max_length=50),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_sell_second',
            field=models.CharField(choices=[('W1', 'W1'), ('D1', 'D1'), ('H1', 'H1'), ('M15', 'M15'), ('M5', 'M5'), ('M1', 'M1'), ('OFF', 'Off')], default='Off', max_length=50),
        ),
    ]
