# Generated by Django 4.2.4 on 2026-02-05 03:21

import common.validation_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0045_configuration_stock_config_time_end_buy_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_time_end_sell_second',
            field=models.TextField(default='15:30', null=True, validators=[common.validation_data.validate_time_format]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_time_start_sell_second',
            field=models.TextField(default='09:30', null=True, validators=[common.validation_data.validate_time_format]),
        ),
    ]
