# Generated by Django 4.2.4 on 2026-02-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0046_configuration_stock_config_time_end_sell_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stock_config_is_use_time_to_buy_first',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_is_use_time_to_buy_second',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_is_use_time_to_sell_first',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stock_config_is_use_time_to_sell_second',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
