# Generated by Django 4.2.4 on 2026-03-25 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0047_configuration_stock_config_is_use_time_to_buy_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_add_price_buy',
            field=models.FloatField(default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_add_price_sell',
            field=models.FloatField(default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_slippage_buy',
            field=models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stock_config_slippage_sell',
            field=models.FloatField(default=0.05, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
