# Generated by Django 4.2.4 on 2026-03-25 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0048_alter_configuration_stock_config_add_price_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='level',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
