# Generated by Django 5.0.6 on 2024-08-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_accounttype_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTradingLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'db_table': 'account_limits_trading',
            },
        ),
    ]
