# Generated by Django 4.2.4 on 2024-02-15 16:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

def init_data_exchange(apps, schema_editor):
    Exchange = apps.get_model('account', 'Exchange')
    Exchange.objects.create(
        code='vps',
        name= 'smartone.vps',
        exchange_type='vps',
        website='https://smartone.vps.com.vn',
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('alias', models.CharField(default='Khách hàng', max_length=100)),
                ('balance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bot_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_need_otp', models.BooleanField(default=False)),
                ('vps_request_verify_token', models.CharField(null=True)),
                ('vps_hash_password', models.CharField(null=True)),
                ('vps_session_id', models.CharField(null=True)),
                ('vps_channel', models.CharField(default='I', null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('exchange_type', models.CharField(choices=[('VPS', 'vps')], max_length=50)),
                ('website', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.exchange'),
        ),
        migrations.RunPython(init_data_exchange)
    ]
