# Generated by Django 4.2.4 on 2024-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_status',
            field=models.CharField(choices=[('READY_LOGIN', 'Login Success'), ('FAILED_OTP', 'Login Failed'), ('NOT_READY_LOGIN', 'Logout'), ('NOT_ACTIVE_ACCOUNT', 'None')], default='Logout', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('PASSIVE', 'Passive'), ('ACTIVE', 'Active')], default='Active', max_length=100),
        ),
    ]
