# Generated by Django 4.2.4 on 2024-04-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_login_status_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vps_cookie',
            field=models.CharField(null=True),
        ),
    ]
