# Generated by Django 4.2.4 on 2024-04-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_vps_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login_status',
            field=models.CharField(choices=[('LoginSuccess', 'LoginSuccess'), ('LoginFailed', 'LoginFailed'), ('Logout', 'Logout'), ('NotActive', 'NotActive')], default='LoginFailed', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Passive', 'Passive'), ('Active', 'Active')], default='Active', max_length=100),
        ),
    ]
