# Generated by Django 5.0.6 on 2024-06-26 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_initial_account_types(apps, schema_editor):
    AccountType = apps.get_model('account', 'AccountType')
    AccountType.objects.create(
        name='Margin', description='Margin account type')
    AccountType.objects.create(
        name='Normal', description='Normal account type')


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_login_status_alter_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bot_amount',
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField(default=0, validators=[
                 django.core.validators.MinValueValidator(0)])),
                ('balance', models.FloatField(default=0, validators=[
                 django.core.validators.MinValueValidator(0)])),
                ('account_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='account.accounttype')),
                ('main_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'db_table': 'sub_account',
            },
        ),
        migrations.RunPython(create_initial_account_types),
    ]
