# Generated by Django 5.0.6 on 2024-08-14 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accounttype_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='total_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
