# Generated by Django 5.0.6 on 2024-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_subaccount_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
