# Generated by Django 5.1.2 on 2025-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_subaccount_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
