# Generated by Django 5.1.2 on 2025-02-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_is_buy_account_is_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_buy',
            new_name='is_block_buy',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_sell',
            new_name='is_block_sell',
        ),
    ]
