# Generated by Django 5.1.2 on 2025-03-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_is_buy_account_is_block_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_num',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
