# Generated by Django 5.1.2 on 2025-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_account_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='limit_number_stocks',
            field=models.IntegerField(default=10),
        ),
    ]
