# Generated by Django 4.2.4 on 2026-03-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='limit_total_market_value',
            field=models.IntegerField(default=500000000),
        ),
    ]
