# Generated by Django 5.1.2 on 2025-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scheduler_status',
            field=models.BooleanField(default=False),
        ),
    ]
