# Generated by Django 5.1.2 on 2025-03-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0002_user_scheduler_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
