# Generated by Django 5.1.2 on 2025-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0003_user_telegram_bot_token_user_telegram_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bot_token_atc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_channel_id_atc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
