# Generated by Django 5.1.2 on 2025-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0004_user_telegram_bot_token_atc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_bot_token_atc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_channel_id_atc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
